### ISSUE TITLE
Does not work on Mac

### ISSUE THREAD

**Issue by grmcdorman** [grmcdorman/SunlessSeaSaveEditor#1]
The application needs to load 'entities/qualities.json' from the user directory (this is alongside the 'save' directory). Currently, however, it does not have any notion of what this path might be or a way to explicitly load the file. This results, on non-Windows systems, in an unusable UI, as no named data is loaded.

Two things should be done to address this:
1. Construct an appropriate default path for Mac.
2. Provide some menu entry to explicitly load this file.

**Comment by spkane** [comment]
Pull request #4 should resolve this issue.

**Comment by grmcdorman** [comment]
Thanks, spkane. Merged (and tweaked a tad to display a dialog instead of printing a message).

It's also kinda hard for me to test on Macs, given that I don't have access to one :)

 I note you include Linux support, but Sunless Sea is not listed on Steam as supporting Linux. Doesn't hurt, though.
